$ANSIBLE_VAULT;1.1;AES256
66666233363838626261303363616637363133333361326665353438306437633864316539623363
6461353865663564336264313862363030363562356230610a646265623861616231613530303533
37326566663034666663366439353233303835303638383561326232313763306664663961373039
6466373837646536340a336234396161313134643536316538626334376330646361373064316231
66336662346631353562366235383165376531386461356132323563343937343635376265383431
35353435663964633238303836376538323133393831333964356135643035383934363637393037
64316466616661633361343365656262613030303163633235376439326562393733333663323636
36326534343433633064
