---
- name: Ensure apt key is not present in trusted.gpg.d
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/docker.asc
    state: absent

- name: Ensure old apt source list is not present in /etc/apt/sources.list.d
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/download_docker_com_linux_{{ docker_apt_ansible_distribution | lower }}.list"
    state: absent

# See https://docs.docker.com/engine/install/debian/#uninstall-old-versions
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name: "{{ docker_obsolete_packages }}"
    state: absent

- name: Ensure broken deb822 repo file is not present
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/docker.sources"
    state: absent

- name: Ensure legacy repo file is not present.
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/docker.list"
    state: absent

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - ca-certificates
      - python3-debian
    state: present

- name: Ensure prerequisites for Docker APT repo
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create keyrings directory if needed
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Add or remove Docker repository
  ansible.builtin.deb822_repository:
    name: "{{ docker_apt_filename }}"
    types: deb
    uris: "{{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }}"
    suites: "{{ docker_apt_suite }}"
    components: "{{ docker_apt_release_channel }}"
    signed_by: "/etc/apt/keyrings/docker.asc"
    state: "{{ 'present' if docker_add_repo | bool else 'absent' }}"
  notify: apt update

- name: Ensure handlers are notified immediately to update the apt cache.
  ansible.builtin.meta: flush_handlers
